site_name: Linux
site_author: "Natalia Marigliano Zelaya"
site_url: https://natmarzel.github.io/practica4-MKDocs/
docs_dir: 'md'
site_dir: 'docs'
extra_css:
  - css/styles.css
nav:
  - Inicio: index.md
  - Conceptos básicos:
    - Introducción: conceptos_basicos.md
    - Scripts: scripts.md
    - Sintaxis: sintaxis.md
    - Comodines: comodines.md
theme: readthedocs
markdown_extensions:
  - admonition
